# Dockerfile (универсальный)
FROM eclipse-temurin:17-jdk-jammy as builder
WORKDIR /app
COPY api/pom.xml .
COPY api/src ./src
RUN apt-get update && \
    apt-get install -y maven && \
    mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]